### ISSUE TITLE
Update `.github/workflows/lint.yml` to use Go 1.23 and more recent version of golanci-lint

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/oss-repo-template-golang#54]
We should update the linter GitHub workflow file to use Go version 1.23 and also use the latest version of golanci-lint-action, which i believe is 6.1.1.

Ex:

This 
```
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: v1.57.2
          args: --timeout 15m
```

should become this
```
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: v1.61.0
          args: --timeout 15m
```
